blank_backstitch <-
  list(
  .setdims = list(xmin = 0,
                  xmax = 0,
                  ybase = 0,
                  ymin = 0,
                  ymax = 0,
                  spacing = 0),
  A = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  B = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  C = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  D = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  E = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  "F" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  G = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  H = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  "I" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  J = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  K = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  L = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  M = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  N = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  O = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  P = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  Q = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  R = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  S = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  "T" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  U = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  V = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  W = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  X = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  Y = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  Z = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  a = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  b = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  "c" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  d = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  e = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  f = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  g = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  h = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  i = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  j = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  k = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  l = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  m = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  n = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  o = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  p = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  q = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  r = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  s = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  t = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  u = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  v = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  w = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  x = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  y = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  z = data.frame(x    = c(0),
                 xend = c(0),
                 y    = c(0),
                 yend = c(0)),
  "0" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  "1" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  "2" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  "3" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  "4" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  "5" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  "6" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  "7" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  "8" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  "9" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  "?" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  "!" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  "." = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  "," = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  "-" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0)),
  ";" = data.frame(x    = c(0),
                   xend = c(0),
                   y    = c(0),
                   yend = c(0))
)
